
---

# =============================================================================
# Dependabot Configuration
# =============================================================================

version: 2

updates:

  # Git Submodule dependencies
  # ===========================================================================

  - 
    package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-gitsubmodule"
      include: "scope"
    labels:
      - "dependencies"
      - "gitsubmodule"



  # GitHub Actions dependencies
  # ===========================================================================

  - 
    package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"


  # NPM dependencies
  # ===========================================================================

  - 
    package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "npm"
    labels:
      - "dependencies"
      - "npm"


  # Docker dependencies
  # ===========================================================================

  - 
    package-ecosystem: "docker"
    directory: "/src/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-docker"
    labels:
      - "dependencies"
      - "docker"


  # devContainer dependencies
  # ===========================================================================

  - 
    package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-devcontainer"
    labels:
      - "dependencies"
      - "devcontainer"

  - 
    package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-devcontainer"
    labels:
      - "dependencies"
      - "devcontainer"


  # PIP dependencies
  # ===========================================================================

  - 
    package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    target-branch: "main"
    commit-message:
      prefix: "dependabot-pip"
    labels:
      - "dependencies"
      - "pip"
