
---

name: Bug Report
description: File a bug report to help us improve.
title: "[BUG]: "
labels: ["Bug", "Needs Triage"]
assignees: []

body:

- 
  type: markdown
  attributes:
    value: |
      ## Bug Report
      - [x] Bug

      Thank you for taking the time to report a bug!
      To help us understand and address the issue promptly, please provide as much detail as possible.      
      Use the sections below to submit a bug **only** if it's related to features in this repo.

      - All bug reports are welcome - we want to fix them!
      - This repo is maintained by volunteers. Please be courteous and patient.
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
      - We accept pull requests. If you know how to fix it - go ahead!

- 
  type: checkboxes
  id: exists
  attributes:
    label: Is there an existing issue for this?
    description: |
      Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
  
- 
  type: input
  id: operating-system
  attributes:
    label: Operating System
    description: |
      What operating system are you using?
    placeholder: |
      e.g. Windows 10, macOS Big Sur
  validations:
    required: true

- 
  type: input
  id: software-version
  attributes:
    label: Software Version
    description: |
      What version of the software are you using?
    placeholder: |
      e.g. 1.0.0
  validations:
    required: true

- 
  type: input
  id: feature
  validations:
    required: true
  attributes:
    label: Sample
    description: |
        Which feature are you having troubles with?

        Use the feature name or URL. We don't want to be spend all this time diagnosing issues about the wrong feature, do we?

- 
  type: textarea
  id: steps-to-reproduce
  attributes:
    label: Steps to reproduce
    description: |
      How do you reproduce this? Please provide as much step-by-step detail as possible.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: true

- 
  type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    description: |
      A clear and concise description of what you expected to happen.
    placeholder: |
      When I do '...', I expect '...'
  validations:
    required: true

- 
  type: textarea
  id: actual-behavior
  attributes:
    label: Actual behavior
    description: |
      A clear and concise description of what actually happens.
    placeholder: |
      When I do '...', what actually happens is '...'
  validations:
    required: true

- 
  type: textarea
  id: logs
  attributes:
    label: Logs or Error Messages
    description: |
       If possible, include any logs or error messages related to the bug.
    placeholder: |
      "Paste the logs or error messages here"
  validations:
    required: false

- 
  type: input
  id: hardware-specs
  attributes:
    label: Hardware Specifications
    description: |
      Please mention any relevant hardware details, such as CPU, GPU, RAM, etc.
    placeholder: |
      e.g. Intel i5, 8GB RAM, Nvidia GTX 1060
  validations:
    required: false

- 
  type: dropdown
  id: frequency
  attributes:
    label: How often does the issue occur?
    description: |
      How frequently do you encounter this issue?
    options:
      - Every time
      - Occasionally
      - Rarely
      - Just once
  validations:
    required: false

- 
  type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: |
      Add any other context, screenshots, or relevant information about the bug here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
