
---

# =============================================================================
# Header
# =============================================================================

name: Feature Request
description: Request a new feature from the community
# title: "[FEATURE]: "
labels: ['Needs: Triage :mag:', 'type:feature-request', 'Help wanted']
# assignees: []


# =============================================================================
# Body
# =============================================================================

body:

# Introduction
# =============================================================================

- 
  type: markdown
  attributes:
    value: |

      Thank you for making a request! Use the sections below to submit a request **only** for a new feature.

      - Requests that do not follow the below template will automatically be closed
      - All requests are welcome - the more the merrier!
      - This repo is maintained by volunteers. Please be courteous and patient.
      - Remember to include sufficient details and context.
      - If you have multiple requests submit them separately so we can track resolution.
      - We accept pull requests. If you know how to make it - go ahead!


# Details
# =============================================================================

- 
  type: textarea
  id: description
  attributes:
    label: Sample description
    description: What should the feature do?
    placeholder: Tell us what you want, what you really, really want.
  validations:
    required: true


# Contribute
# =============================================================================

- type: dropdown
  id: willing-to-help
  attributes:
    label: Are you willing to help?
    description: Would you be willing to help whoever decides to take this on?
    options:
      - "Yes"
      - "No"
  validations:
    required: true
